name: Notion Board
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Notion Board
        uses: ./
        env: 
          NOTION_API_KEY: ${{secrets.NOTION_TOKEN}}
          NOTION_DATABSE: ${{secrets.NOTION_DATABSE}}
          