name: Notion Board
on:
  issues:
  issue_comment:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Board
        uses: ./
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABSE: ${{ secrets.NOTION_DATABSE }}
          